version: "3"
services:

## Query Engine ##
  trino:
    image: trinodb/trino
    container_name: trino
    hostname: trino
    ports:
      - 8001:8080
    volumes:
      - ./catalog:/etc/trino/catalog
      - ../keys/service-account-dev.json:/opt/keys/service-account-dev.json
    networks:
      - data-network

networks:
  data-network:
    external: true