version: "3"
services:

## Visualization ##
  metabase:
    image: metabase-image
    build:
      context: .
      dockerfile: Dockerfile
    container_name: metabase
    hostname: metabase
    volumes:
      - metabase:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: mysecretpassword
      MB_DB_HOST: metabase-db
    depends_on:
      - metabase-db
    networks:
      - data-network
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

  metabase-db:
    image: postgres:15
    container_name: metabase-db
    hostname: metabase-db
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabaseappdb
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - metabase-db:/var/lib/postgresql
    networks:
      - data-network

volumes:
  metabase:
  metabase-db:

networks:
  data-network:
    external: true